version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_inventory
      - DB_USERNAME=root
      - DB_PASSWORD=unsia

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: unsia
      MYSQL_DATABASE: db_inventory
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
